service: ksk-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  first:
    handler: handler.hello
    destinations:
      onSuccess: successLambda
      onFailure: failureLambda
  successLambda:
    handler: handler.successLambda
  failureLambda:
    handler: handler.failureLambda

