service: stepfunctions-test
frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221

package:
  patterns:
    - '!venv/**'

plugins:
  - serverless-python-requirements
  - serverless-step-functions

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  first-lambda:
    handler: handler.first_lambda

stepFunctions:
  stateMachines:
    LambdaComb:
      name: LambdaComb
      definition: ${file(./sf.json)}
